services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
  ports:
   - "10051:10051"
  environment:
   - DB_SERVER_HOST=mysql-server
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix_pwd
   - MYSQL_ROOT_PASSWORD=root_pwd
  depends_on:
   - mysql-server
  networks:
   - zbx_net_backend
   - zbx_net_frontend

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.2-latest
  ports:
   - "80:8080"
  environment:
   - ZBX_SERVER_HOST=zabbix-server
   - DB_SERVER_HOST=mysql-server
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix_pwd
  depends_on:
   - mysql-server
   - zabbix-server
  networks:
   - zbx_net_backend
   - zbx_net_frontend

 mysql-server:
  image: mysql:8.0
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --default-authentication-plugin=mysql_native_password
  environment:
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix_pwd
   - MYSQL_ROOT_PASSWORD=root_pwd
  volumes:
   - mysql_data:/var/lib/mysql
  networks:
   - zbx_net_backend

networks:
  zbx_net_frontend:
    driver: bridge
  zbx_net_backend:
    driver: bridge
    internal: true

volumes:
  mysql_data: