services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
    env_file: .env
    volumes:
        - ./wp-content:/var/www/html/wp-content

  mysql:
    image: mysql:8.4.6
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
        - ./mysql_data:/var/lib/mysql
        - ./mysql_log:/var/log/mysql
      