name: Docker Build CI

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t alpine-server:latest ./alpine
    
    - name: Test Docker image
      run: docker run --rm alpine-server:latest echo "Build successful"