name: CI Development Environment Build CI

on:
  push:
  pull_request:
    branches: [ main, master ]
    paths: [ 'ci-development/**' ]

jobs:
  ci-development-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Start CI/CD services
      run: docker compose -f ci-development/docker-compose.yml up -d
      
    - name: Wait for services
      run: |
        sleep 30
        docker compose -f ci-development/docker-compose.yml ps
      
    - name: Run tests
      run: docker compose -f ci-development/docker-compose.yml run --rm python bash -c "pip install selenium && python /tests/run_tests.py"
      
    - name: Stop services
      run: docker compose -f ci-development/docker-compose.yml down